apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: oke-atp-handson-db
spec:
  details:
    compartmentOCID: <ご自身のコンパートメントOCID>
    dbName: okeatp
    displayName: oke-atp-handson-db
    cpuCoreCount: 1
    licenseModel: LICENSE_INCLUDED
    wallet:
      name: okeatp
      password:
        k8sSecret:
          name: wallet-passwd
    adminPassword:
      k8sSecret:
        name: admin-passwd
    dataStorageSizeInTBs: 1
