apiVersion: database.oracle.com/v1alpha1
kind: AutonomousDatabase
metadata:
  name: oke-atp-handson-db
spec:
  action: Create
  details:
    compartmentId: <自身のコンパートメントOCID>
    dbName: okeatp
    displayName: oke-atp-handson-db
    computeModel: ECPU
    computeCount: 2.0
    licenseModel: LICENSE_INCLUDED
    adminPassword:
      k8sSecret:
        name: admin-passwd
    dataStorageSizeInTBs: 1
  wallet:
    name: okeatp
    password:
      k8sSecret:
        name: wallet-passwd
